-- DROP FUNCTION public.f_sbi_escr012_a(varchar, varchar, varchar, date, date, varchar);

CREATE OR REPLACE FUNCTION public.f_sbi_escr012_a(p_tp_entsai character varying, p_ds_grpemit character varying, p_cd_empresa character varying, p_dt_dataini date, p_dt_datafin date, p_ds_colunas character varying)
 RETURNS text
 LANGUAGE plpgsql
AS $function$ DECLARE

   V_RESULT  text;
   I_EMPRESA INTEGER;
   V_UNION_ESCRITA text;
   V_UNION_EXISTS text ;
   v_ds_colunas varchar(50);
   v_ds_negocio varchar(50);
   cur record;

begin
   V_RESULT := ' ' ;     
   V_UNION_EXISTS := ' ' ;
   V_UNION_ESCRITA := ' ' ;
   v_ds_colunas := p_ds_colunas ;
 
   i_empresa := 0 ;
   
   FOR CUR IN ( SELECT *
                  FROM SINTAB12
                  inner JOIN pg_stat_user_tables ON   SCHEMANAME = 'public'  AND relname = 'escmv' || trim(to_char(NTAB_EMITENT_12, '000'))
                   WHERE ( substr(P_DS_GRPEMIT,1,2) = '00' or substr( P_DS_GRPEMIT ,1,2) = trim(to_char( ntab_grpemit_12 ,'00')) )
                      and ( trim(to_char(NTAB_EMITENT_12, '000')) =  p_cd_empresa or p_cd_empresa = '000')
   )
     LOOP
         if V_UNION_ESCRITA <> ' ' then
            V_UNION_ESCRITA := V_UNION_ESCRITA || ' UNION ALL ' ;
         end if ;
         
         if V_UNION_EXISTS <> ' ' then
            V_UNION_EXISTS := V_UNION_EXISTS || ' UNION ALL ' ;
         end if ;
         
            V_UNION_EXISTS  := V_UNION_EXISTS ||' select '|| trim(to_char(cur.NTAB_EMITENT_12, '000')) ||' as EMPRESA , '||
                                                '              ESCM_TIPOREG_1 , '||
                                                '              ESCM_EMITENT_1 , '||
                                                '              ESCM_NRONOTA_1 ,' ||
                                                '              ESCM_SERNOTA_1 , '||
                                                '              ESCM_ESPNOTA_1 '  ||
                                                '   from escmv'|| trim(to_char(cur.NTAB_EMITENT_12, '000')) || CHR(13) ;
           
             V_UNION_ESCRITA := V_UNION_ESCRITA ||'    SELECT   '|| trim(to_char(cur.NTAB_EMITENT_12, '000')) ||  ' AS EMPRESA   '||chr(13)||
                                                '       ,ESCM_USUARIO_1  AS CD_USER                                                                         '||chr(13)||
                                                    '        ,ESCM_TIPOREG_1 AS TIPO                                                                            '||chr(13)||
                                                '        ,ESCM_NRONOTA_1 AS NOTA                                                                            '||chr(13)||
                                                    '        ,ESCM_SERNOTA_1 AS SERIE                                                                            '||chr(13)||
                                                '        ,ESCM_ESPNOTA_1 AS ESPECIE                                                                          '||chr(13)||
                                                '        ,ESCM_NATOPER_1 AS CFOP                                                                             '||chr(13)||
                                                '        ,ESCM_EMITENT_1 AS CD_EMITENTE                                                                      '||chr(13)||
                                                '        ,ESCM_DESTINA_1 AS DESTINATARIO                                                                     '||chr(13)||
                                                '        ,ESCM_NOMEMDE_1 AS NOME                                                                             '||chr(13)||
                                                '        ,ESCM_INSCRIC_1 AS IE                                                                               '||chr(13)||
                                                '        ,ESCM_SIGLEST_1 AS UF                                                                               '||chr(13)||
                                                '        ,ESCM_DATLANC_1 AS DATA_LANCAMENTO                                                                  '||chr(13)||
                                                '        ,ESCM_DATEMIS_1 AS DATA_EMISSAO                                                                     '||chr(13)||
                                                '        ,ESCM_DATENTR_1 AS DATA_ENTRADA                                                                     '||chr(13)||
                                                '        ,ESCM_TIPOLAN_1 AS tp_lanc                                                                          '||chr(13)||
                                                '        ,CITE_SEQNOTA_1 AS SEQUENCIA                                                                        '||chr(13)||
                                                '        ,CITE_CODPROD_1 AS CODIGO                                                                           '||chr(13)||
                                                '        ,CITE_DESCRIC_1 AS DESCRICAO                                                                        '||chr(13)||
                                                '        ,LPAD(CAST(CITE_CODTRIB_1 AS VARCHAR),3,''0'') AS CST                                               '||chr(13)||
                                                '        ,CITE_CODINBM_1 AS NCM                                                                              '||chr(13)||
                                                '        ,CITE_QUANTID_1 AS QUANTIDADE                                                                       '||chr(13)||
                                                '        ,CITE_VALTOTA_1 + 0 + 0 -  CITE_DESCONT_1  AS VALOR_TOTAL                                           '||chr(13)||
                                                '        ,CITE_BASEICM_1 AS BASE_ICMS                                                                        '||chr(13)||
                                                '        ,CITE_ALIQICM_1 AS ALIQ_ICMS                                                                        '||chr(13)||
                                                '        ,round( CITE_BASEICM_1 * CITE_ALIQICM_1  / 100 , 2) + cite_icmmono_1  AS VALOR_ICMS                 '||chr(13)||
                                                '        ,CASE WHEN ESCM_ISENICM_1 > 0 THEN                                                                  '||chr(13)||
                                                '                (  CITE_VALTOTA_1 + CITE_VALOIPI_1 + 0 -  CITE_DESCONT_1 ) - CITE_BASEICM_1                 '||chr(13)||
                                                '         ELSE 0 END   AS ICMS_ISENTO                                                                        '||chr(13)||
                                                '        ,CASE WHEN ESCM_OUTRICM_1 > 0 THEN                                                                  '||chr(13)||
                                                '                (  CITE_VALTOTA_1 + CITE_VALOIPI_1 + 0 -  CITE_DESCONT_1 ) - CITE_BASEICM_1                 '||chr(13)||
                                                '         ELSE 0 END  AS ICMS_OUTROS                                                                         '||chr(13)||
                                                '        ,CITE_BASESUB_1 AS BASE_ICMS_ST                                                                     '||chr(13)||
                                                '        ,0 AS MVA                                                                                           '||chr(13)||
                                                '        ,0 AS VALOR_ICMS_ST                                                                                 '||chr(13)||
                                                '        ,CITE_PERCIPI_1 AS ALIQUOTA_IPI                                                                     '||chr(13)||
                                                '        ,CITE_VALOIPI_1 AS VALOR_IPI                                                                        '||chr(13)||
                                                '        ,CITE_VALTOTA_1 + CITE_VALOIPI_1 + 0 -  CITE_DESCONT_1  AS VALOR_CONTABIL                           '||chr(13)||
                                                '        ,cast( CITE_CSTCOFI_1 as varchar ) AS CST_COFINS                                                    '||chr(13)||
                                                '        ,CITE_BASECOF_1 AS BASE_COFINS                                                                      '||chr(13)||
                                                '        ,CITE_ALIQCOF_1 AS ALIQ_COFINS                                                                      '||chr(13)||
                                                '        ,CITE_VALOCOF_1 AS VALOR_COFINS                                                                        '||chr(13)||
                                                '        ,cast( CITE_CSTPISS_1 as varchar) AS CST_PIS                                                        '||chr(13)||
                                                '        ,CITE_BASEPIS_1 AS BASE_PIS                                                                         '||chr(13)||
                                                '        ,CITE_ALIQPIS_1 AS ALIQ_PIS                                                                         '||chr(13)||
                                                '        ,CITE_VALOPIS_1 AS VALOR_PIS                                                                        '||chr(13)||
                                                '        ,ITED_VBCUFDEST_1 AS BASE_DIF_DEST                                                                  '||chr(13)||
                                                '        ,ITED_VICMSUFDEST_1 AS DIFAL_DEST                                                                   '||chr(13)||
                                                '        ,ITED_VBCUFDEST_1 AS BASE_DIF_REMET                                                                 '||chr(13)||
                                                '        ,ITED_VICMSUFREMET_1 AS DIFAL_REMET                                                                 '||chr(13)||
                                                '        ,ITED_VBCUFDEST_1 AS BASE_FCP                                                                       '||chr(13)||
                                                '        ,ITED_VFCPUFDEST_1 AS VALOR_FCP                                                                     '||chr(13)||
                                                '        ,ESCM_CHAVNFE_1 AS CHAVE_NFE                                                                        '||chr(13)||
                                                '        ,CITE_NATBCRE_1 AS CD_NBCR                                                                          '||chr(13)||
                                                '        ,escm_basrobs_1 AS base_icms_comp                                                                   '||chr(13)||
                                                '        ,escm_icmrobs_1 AS valor_icms_comp                                                                  '||chr(13)||
                                                '        FROM ESCMV'|| trim(to_char(cur.NTAB_EMITENT_12, '000'))                                              ||chr(13)||
                                                '        LEFT JOIN ESCIT'|| trim(to_char(cur.NTAB_EMITENT_12 , '000')) ||' ON ESCM_SITUNOT_1 = CITE_SITUNOT_1 AND '||chr(13)||
                                                '                      ESCM_TIPOREG_1 = CITE_TIPOREG_1 AND                                                   '||chr(13)||
                                                '                      ESCM_NRONOTA_1 = CITE_NRONOTA_1 AND                                                   '||chr(13)||
                                                '                      ESCM_SERNOTA_1 = CITE_SERNOTA_1 AND                                                   '||chr(13)||
                                                '                      ESCM_ESPNOTA_1 = CITE_ESPNOTA_1 AND                                                   '||chr(13)||
                                                '                      ESCM_NATOPER_1 = CITE_NATOPER_1 AND                                                   '||chr(13)||
                                                '                      ESCM_EMITENT_1 = CITE_EMITENT_1                                                         '||chr(13)||
                                                '        LEFT JOIN ESCID'|| trim(to_char(cur.NTAB_EMITENT_12, '000')) ||' ON   CITE_SITUNOT_1 =   ITED_SITUNOT_1  AND  '||chr(13)||
                                                '                    CITE_TIPOREG_1 =   ITED_TIPOREG_1  AND                                                  '||chr(13)||
                                                '                    CITE_NRONOTA_1 =   ITED_NRONOTA_1  AND                                                  '||chr(13)||
                                                '                    CITE_SERNOTA_1 =   ITED_SERNOTA_1  AND                                                  '||chr(13)||
                                                '                    CITE_ESPNOTA_1 =   ITED_ESPNOTA_1  AND                                                  '||chr(13)||
                                                '                    CITE_NATOPER_1 =   ITED_NATOPER_1  AND                                                  '||chr(13)||
                                                '                    CITE_EMITENT_1 =   ITED_EMITENT_1  AND                                                  '||chr(13)||
                                                '                    CITE_SEQNOTA_1 =   ITED_SEQNOTA_1                                                        '||chr(13)||
                                                '        WHERE ESCM_SITUNOT_1 <> ''C''                                                                         '||chr(13)||
                                                '         AND CITE_SEQNOTA_1  < 900                                                                          '
                                                '         AND escm_servico_1 = 0                                                                          '
                                                ;
        
     END LOOP;
 
       V_RESULT := V_RESULT ||
                            '          /*ENTRADAS ESTOQUE*/                                                                                                                                                                         '||CHR(13) ||
                            '         SELECT ''E'' AS "TIPO"                                                                                                                                                                         '||CHR(13) ||
                            '         ,''NOTENTI, NOTENT '' AS "ARQUIVO#"                                                                                                                                                            '||CHR(13) ||
                            '                                                                                                                                                                                                        '||CHR(13) ||
                            '        , CASE WHEN                                                                                                                                                                                     '||CHR(13) ||
                            '          CASE WHEN ( ENTI_basepis_1 > 0 OR enti_basecof_1  > 0 ) AND NTAB_PISCOFI_23 = 0  THEN 0                                                                                                       '||CHR(13) ||
                            '                ELSE 1 END  =  0 THEN   ''#EC7063''  END  AS "SBI_COLOR"                                                                                                                                '||CHR(13) ||
                            '        ,EMITENTE AS "EMPRESA*"                                                                                                                                                                         '||CHR(13) ||
                            '        ,ENTI_NRONOTA_1             AS  "+NOTA"                                                                                                                                                            '||CHR(13) ||
                            '        ,ENTI_ESPECIE_1         AS  "ESPECIE"                                                                                                                                                              '||CHR(13) ||
                            '        ,ENTI_NATOPER_1             AS  "CFOP"                                                                                                                                                             '||CHR(13) ||
                            '        ,LPAD(CAST(NTAB_CODIGOS_23 AS VARCHAR),3,''0'')||'' - ''||NTAB_DESCRIC_23     AS  "TIPO LANÇAMENTO"                                                                                             '||CHR(13) ||
                            '        ,TENT_DATEMIS_1         AS  "DATA EMISSÃO"                                                                                                                                                         '||CHR(13) ||
                            '        ,TENT_DATPROC_1     AS  "DATA LANÇAMENTO"                                                                                                                                                          '||CHR(13) ||
                            '        ,TENT_RECPDAT_1         AS  "DATA ENTRADA"                                                                                                                                                         '||CHR(13) ||
                            '        ,TENT_FORNECE_1         AS  "EMITENTE/DESTINATARIO"                                                                                                                                                '||CHR(13) ||
                            '        ,NCAD_NOMECLI_2          AS  "NOME"                                                                                                                                                             '||CHR(13) ||
                            '        ,TENT_SIGLEST_1             AS  "UF"                                                                                                                                                               '||CHR(13) ||
                            '        ,TENT_CHAVNFE_1               AS  "CHAVE DE ACESSO"                                                                                                                                             '||CHR(13) ||
                            '        , ENTI_TOTITEM_1 +  enti_valoipi_1 - ENTI_DESCPRO_1 + ENTI_DESPPRO_1 + ENTI_VALSUBS_1 + ENTI_FRETPRO_1    AS "VALOR CONTABIL$SUM"                                                               '||CHR(13) ||
                            '        ,ENTI_CODPROD_1         AS  "CODIGO"                                                                                                                                                               '||CHR(13) ||
                            '        ,ENTI_DESCRIC_1||ENTI_DESCRI2_1         AS "DESCRIÇÃO"                                                                                                                                             '||CHR(13) ||
                            '        ,ENTI_CLAFISC_1             AS "NCM"                                                                                                                                                               '||CHR(13) ||
                            '        ,ENTI_QUANTID_1             AS "QUANTIDADE$Q"                                                                                                                                                      '||CHR(13) ||
                            '        ,ENTI_VALUNIT_1                  AS "UNITARIO$"                                                                                                                                                 '||CHR(13) ||
                            '        ,ENTI_TOTITEM_1   AS "VALOR TOTAL$SUM"                                                                                                                                                          '||CHR(13) ||
                            '        ,ENTI_DESCPRO_1   AS "DESCONTO$SUM"                                                                                                                                                             '||CHR(13) ||
                            '        ,ENTI_FRETPRO_1  AS "VALOR FRETE$SUM"                                                                                                                                                           '||CHR(13) ||
                            '        ,ENTI_DESPPRO_1 AS "DESPESAS ACESSÓRIAS$SUM"                                                                                                                                                    '||CHR(13) ||
                            '        ,ENTI_BASEICM_1 + enti_basprop_1  AS "BASE ICMS$SUM"                                                                                                                                                              '||CHR(13) ||
                            '        ,CAST(ENTI_NACIONA_1 AS VARCHAR)||CAST(ENTI_SITRIBU_1 AS VARCHAR) AS "CST"                                                                                                                                                '||CHR(13) ||
                            '        ,enti_aliquot_1  AS  "ALIQ. ICMS"                                                                                                                                                               '||CHR(13) ||
                            '        ,ENTI_VALOICM_1 + enti_icmprop_1    AS "VALOR ICMS$SUM"                                                                                                                                                            '||CHR(13) ||
                            '        ,case when enti_baseicm_1 = 0 or enti_baseicm_1 < ENTI_TOTITEM_1 +  enti_valoipi_1 - ENTI_DESCPRO_1 + ENTI_DESPPRO_1 + ENTI_VALSUBS_1 + ENTI_FRETPRO_1  then                                    '||CHR(13) ||
                            '             case when ntab_isenliv_24 = 1 then ( ENTI_TOTITEM_1 +  enti_valoipi_1 - ENTI_DESCPRO_1 + ENTI_DESPPRO_1 + ENTI_VALSUBS_1 + ENTI_FRETPRO_1 ) - enti_baseicm_1                               '||CHR(13) ||
                            '                   else 0 end                                                                                                                                                                           '||CHR(13) ||
                            '         else 0 end          AS "ICMS-ISENTO$SUM"                                                                                                                                                       '||CHR(13) ||
                            '        ,case when enti_baseicm_1 = 0 or enti_baseicm_1 < ENTI_TOTITEM_1 +  enti_valoipi_1 - ENTI_DESCPRO_1 + ENTI_DESPPRO_1 + ENTI_VALSUBS_1 + ENTI_FRETPRO_1  then                                    '||CHR(13) ||
                            '             case when ntab_isenliv_24 = 2 then ( ENTI_TOTITEM_1 +  enti_valoipi_1 - ENTI_DESCPRO_1 + ENTI_DESPPRO_1 + ENTI_VALSUBS_1 + ENTI_FRETPRO_1 ) - enti_baseicm_1                               '||CHR(13) ||
                            '                   else 0 end                                                                                                                                                                           '||CHR(13) ||
                            '         else 0 end          AS "ICMS-OUTROS$SUM"                                                                                                                                                        '||CHR(13) ||
                            '        ,ENTI_BASESUB_1 AS "BASE ICMS ST$SUM"                                                                                                                                                           '||CHR(13) ||
                            '        ,ENTI_VALSUBS_1 AS "VALOR ICMS ST$SUM"                                                                                                                                                          '||CHR(13) ||
                            '        ,enti_baseipi_1 AS "BASE_IPI$SUM"                                                                                                                                                               '||CHR(13) ||
                            '        ,enti_CSTIPII_1 AS "CST IPI"                                                                                                                                                                    '||CHR(13) ||
                            '        ,ENTI_PERCIPI_1 AS "ALIQ. IPI"                                                                                                                                                                  '||CHR(13) ||
                            '        ,enti_valoipi_1  AS "VALOR IPI$SUM"                                                                                                                                                             '||CHR(13) ||
                            '        ,enti_basepis_1 AS "BASE PIS$SUM"                                                                                                                                                               '||CHR(13) ||
                            '        ,enti_cstpiss_1 AS "CST PIS"                                                                                                                                                                    '||CHR(13) ||
                            '        ,enti_aliqpis_1  AS "ALIQ. PIS"                                                                                                                                                                 '||CHR(13) ||
                            '        ,enti_valopis_1 AS "VALOR PIS$SUM"                                                                                                                                                              '||CHR(13) ||
                            '        ,enti_basecof_1  AS "BASE COFINS$SUM"                                                                                                                                                           '||CHR(13) ||
                            '        , enti_cstcofi_1  AS "CST COFINS"                                                                                                                                                               '||CHR(13) ||
                            '        ,enti_aliqcof_1 as "ALIQ. COFINS"                                                                                                                                                               '||CHR(13) ||
                            '        ,enti_valocof_1  AS "VALOR COFINS$SUM"                                                                                                                                                            '||CHR(13) ||
                            '        ,enti_vbcufdest_1  AS "BASE_DIF_DEST$SUM"                                                                                                                                                            '||CHR(13) ||
                            '        ,enti_vicmsufdest_1 AS "DIFAL_DEST$SUM"                                                                                                                                                            '||CHR(13) ||
                            '        ,enti_vbcufdest_1 AS "BASE_DIF_REMET$SUM"                                                                                                                                                            '||CHR(13) ||
                            '        ,enti_vicmsufremet_1 AS "DIFAL_REMET$SUM"                                                                                                                                                            '||CHR(13) ||
                            '        ,enti_vbcufdest_1 AS "BASE_FCP$SUM"                                                                                                                                                            '||CHR(13) ||                           
                            '        ,enti_vfcpufdest_1 AS "VALOR_FCP$SUM"                                                                                                                                                            '||CHR(13) ||                                                                                  
                            '        ,enti_basrobs_1  AS "BASE ICMS ST COMPL$SUM"                                                                                                                                                           '||CHR(13) ||                                                                                  
                             '       ,enti_icmrobs_1  AS "VALOR ICMS ST COMPL$SUM"                                                                                                                                                            '||CHR(13) ||                                                                                                                                    
                            '        FROM NOTENTI                                                                                                                                                                                    '||CHR(13) ||
                            '        LEFT JOIN NOTENT ON             TENT_EMITENT_1 = ENTI_EMITENT_1 AND                                                                                                                              '||CHR(13) ||
                            '                            TENT_FORNECE_1 =  ENTI_FORNECE_1  AND                                                                                                                                       '||CHR(13) ||
                            '                            TENT_NRONOTA_1 =  ENTI_NRONOTA_1 AND                                                                                                                                        '||CHR(13) ||
                            '                            TENT_SERNOTA_1 = ENTI_SERNOTA_1 AND                                                                                                                                         '||CHR(13) ||
                            '                            TENT_ESPECIE_1 = ENTI_ESPECIE_1                                                                                                                                                '||CHR(13) ||
                            '        LEFT JOIN V_EMITENTE ON TENT_EMITENT_1 = COD                                                                                                                                                    '||CHR(13) ||
                            '        LEFT JOIN SINCAD     ON  TENT_FORNECE_1  = NCAD_CGCOCPF_2                                                                                                                                       '||CHR(13) ||
                            '        LEFT JOIN SINTAB01   ON  NCAD_CODMUNI_2 = NTAB_CODMUNI_1                                                                                                                                        '||CHR(13) ||
                            '        LEFT JOIN SINTAB24 ON ENTI_TIPONOT_1 = NTAB_TIPONFS_24                                                                                                                                          '||CHR(13) ||
                            '        LEFT JOIN SINTAB23 ON NTAB_CODLIVR_24 = NTAB_CODIGOS_23                                                                                                                                         '||CHR(13) ||
                            '                                                                                                                                                                                                        '||CHR(13) ||
                            '        WHERE     TENT_SITUACA_1 <> ''C''                                                                                                                                                                '||CHR(13) ||
                            '                  AND ( ''E'' = SUBSTR( '||''''|| p_tp_entsai ||'''' ||' ,1,1) )                                                                                                                              '||CHR(13) ||
                            '                  AND  TENT_RECPDAT_1 BETWEEN   '|| ''''||p_dt_dataini||'''' ||'  AND ' ||''''|| p_dt_datafin ||'''' || '                                                                                                                      '||CHR(13) ||
                            '                    and (  ENTI_EMITENT_1 = CAST( SUBSTR( '||''''||p_cd_empresa||'''' ||' , 1,3) AS INTEGER) OR   CAST( SUBSTR( '||''''||p_cd_empresa||'''' ||' , 1,3) AS INTEGER)  = 0 )                                             '||CHR(13) ||
                            '                  AND  EXISTS ( SELECT 1 FROM (  ' || V_UNION_EXISTS || ' ) ESCMV WHERE                                                                                                                                  '||CHR(13) ||
                            '                                empresa  = ENTI_EMITENT_1 AND                                                                                                                                           '||CHR(13) ||
                            '                                ESCM_TIPOREG_1 =  ''E'' AND                                                                                                                                               '||CHR(13) ||
                            '                                ESCM_EMITENT_1 =  ENTI_FORNECE_1  AND                                                                                                                                   '||CHR(13) ||
                            '                                ESCM_NRONOTA_1 =  ENTI_NRONOTA_1 AND                                                                                                                                    '||CHR(13) ||
                            '                                ESCM_SERNOTA_1 = ENTI_SERNOTA_1 AND                                                                                                                                     '||CHR(13) ||
                            '                                ESCM_ESPNOTA_1 = ENTI_ESPECIE_1      )                                                                                                                                     '||CHR(13) ||
                            '                                                                                                                                                                                                        '||CHR(13) ||
                            '                                                                                                                                                                                                        '||CHR(13) ||
                            '        UNION ALL                                                                                                                                                                                       '||CHR(13) ||
                            '        /*SAIDAS*/                                                                                                                                                                                      '||CHR(13) ||
                            '         SELECT ''S'' AS "TIPO"                                                                                                                                                                           '||CHR(13) ||
                            '         ,''NOTSAII, NOTSAI '' AS "ARQUIVO#"                                                                                                                                                                 '||CHR(13) ||
                            '        , CASE WHEN                                                                                                                                                                                     '||CHR(13) ||
                            '          CASE WHEN ( SAII_basepis_1 > 0 OR SAII_basecof_1  > 0 ) AND NTAB_PISCOFI_23 = 0  THEN 0                                                                                                       '||CHR(13) ||
                            '                ELSE 1 END  =  0 THEN    ''#EC7063''  END  AS "SBI_COLOR"                                                                                                                                 '||CHR(13) ||
                            '        , EMITENTE AS "EMPRESA*"                                                                                                                                                                        '||CHR(13) ||
                            '        ,SAII_NRONOTA_1             AS  "NOTA"                                                                                                                                                             '||CHR(13) ||
                            '        ,TSAI_ESPNOTA_1         AS  "ESPECIE"                                                                                                                                                              '||CHR(13) ||
                            '        ,SAII_NATOPER_1             AS  "CFOP"                                                                                                                                                             '||CHR(13) ||
                            '        ,LPAD(CAST(NTAB_CODIGOS_23 AS VARCHAR),3,''0'')||'' - ''||NTAB_DESCRIC_23     AS  "TIPO LANÇAMENTO"                                                                                                 '||CHR(13) ||
                            '        ,TSAI_EMISDAT_1         AS  "DATA EMISSÃO"                                                                                                                                                         '||CHR(13) ||
                            '        ,TSAI_EMISDAT_1     AS  "DATA LANÇAMENTO"                                                                                                                                                          '||CHR(13) ||
                            '        ,TSAI_EMISDAT_1         AS  "DATA ENTRADA/SAIDA"                                                                                                                                                   '||CHR(13) ||
                            '        ,TSAI_CLIENTE_1         AS  "EMITENTE/DESTINATARIO"                                                                                                                                                '||CHR(13) ||
                            '        ,NCAD_NOMECLI_2          AS  "NOME"                                                                                                                                                             '||CHR(13) ||
                            '        ,TSAI_SIGLEST_1             AS  "UF"                                                                                                                                                               '||CHR(13) ||
                            '        ,TSAI_CHAVNFE_1               AS  "CHAVE DE ACESSO"                                                                                                                                             '||CHR(13) ||
                            '        ,SAII_VALIQUI_1 +  SAII_valoipi_1 - SAII_DESCPRO_1 + SAII_DESPPRO_1 + SAII_VALSUBS_1 + SAII_FRETPRO_1    AS "VALOR CONTABIL$SUM"                                                               '||CHR(13) ||
                            '        ,SAII_CODPROD_1         AS  "CODIGO"                                                                                                                                                               '||CHR(13) ||
                            '        ,SAII_DESCRIC_1||SAII_DESCRI2_1         AS "DESCRIÇÃO"                                                                                                                                             '||CHR(13) ||
                            '        ,SAII_CLAFISC_1             AS "NCM"                                                                                                                                                               '||CHR(13) ||
                            '        ,SAII_QUANTID_1             AS "QUANTIDADE$Q"                                                                                                                                                      '||CHR(13) ||
                            '        ,SAII_VALUNIT_1                  AS "UNITARIO$"                                                                                                                                                 '||CHR(13) ||
                            '        ,SAII_VALIQUI_1   AS "VALOR TOTAL$SUM"                                                                                                                                                          '||CHR(13) ||
                            '        ,SAII_DESCPRO_1   AS "DESCONTO$SUM"                                                                                                                                                             '||CHR(13) ||
                            '        ,SAII_FRETPRO_1  AS "VALOR FRETE$SUM"                                                                                                                                                           '||CHR(13) ||
                            '        ,SAII_DESPPRO_1 AS "DESPESAS ACESSÓRIAS$SUM"                                                                                                                                                    '||CHR(13) ||
                            '        ,SAII_BASEICM_1 AS "BASE ICMS$SUM"                                                                                                                                                              '||CHR(13) ||
                            '        ,TRIM(TO_CHAR(SAII_SITRIBU_1,''000''))     AS "CST"                                                                                                                                                   '||CHR(13) ||
                            '        ,SAII_aliquot_1  AS  "ALIQ. ICMS"                                                                                                                                                               '||CHR(13) ||
                            '        ,SAII_VALOICM_1   AS "VALOR ICMS$SUM"                                                                                                                                                            '||CHR(13) ||
                            '        ,case when SAII_BASEICM_1 = 0 or SAII_BASEICM_1 < SAII_VALIQUI_1 +  SAII_valoipi_1 - SAII_DESCPRO_1 + SAII_DESPPRO_1 + SAII_VALSUBS_1 + SAII_FRETPRO_1   then                                   '||CHR(13) ||
                            '             case when ntab_isenliv_24 = 1 then (SAII_VALIQUI_1 +  SAII_valoipi_1 - SAII_DESCPRO_1 + SAII_DESPPRO_1 + SAII_VALSUBS_1 + SAII_FRETPRO_1 ) - SAII_BASEICM_1                                '||CHR(13) ||
                            '                   else 0 end                                                                                                                                                                           '||CHR(13) ||
                            '         else 0 end          AS "ICMS-ISENTO$SUM"                                                                                                                                                       '||CHR(13) ||
                            '        ,case when SAII_BASEICM_1 = 0 or SAII_BASEICM_1 < SAII_VALIQUI_1 +  SAII_valoipi_1 - SAII_DESCPRO_1 + SAII_DESPPRO_1 + SAII_VALSUBS_1 + SAII_FRETPRO_1   then                                   '||CHR(13) ||
                            '             case when ntab_isenliv_24 = 2 then ( SAII_VALIQUI_1 +  SAII_valoipi_1 - SAII_DESCPRO_1 + SAII_DESPPRO_1 + SAII_VALSUBS_1 + SAII_FRETPRO_1  ) - SAII_BASEICM_1                              '||CHR(13) ||
                            '                   else 0 end                                                                                                                                                                           '||CHR(13) ||
                            '         else 0 end          AS "ICMS-OUTROS$SUM"                                                                                                                                                       '||CHR(13) ||
                            '        ,SAII_BASESUB_1 AS "BASE ICMS ST$SUM"                                                                                                                                                           '||CHR(13) ||
                            '        ,SAII_VALSUBS_1 AS "VALOR ICMS ST$SUM"                                                                                                                                                          '||CHR(13) ||
                            '        ,SAII_bastrip_1 AS "BASE_IPI$SUM"                                                                                                                                                               '||CHR(13) ||
                            '        ,SAII_CSTIPII_1 AS "CST IPI"                                                                                                                                                                    '||CHR(13) ||
                            '        ,SAII_PERCIPI_1 AS "ALIQ. IPI"                                                                                                                                                                  '||CHR(13) ||
                            '        ,SAII_valoipi_1  AS "VALOR IPI$SUM"                                                                                                                                                             '||CHR(13) ||
                            '                                                                                                                                                                                                        '||CHR(13) ||
                            '        ,SAII_basepis_1 AS "BASE PIS$SUM"                                                                                                                                                               '||CHR(13) ||
                            '        ,SAII_cstpiss_1 AS "CST PIS"                                                                                                                                                                    '||CHR(13) ||
                            '        ,SAII_aliqpis_1  AS "ALIQ. PIS"                                                                                                                                                                 '||CHR(13) ||
                            '        ,SAII_valopis_1 AS "VALOR PIS$SUM"                                                                                                                                                                 '||CHR(13) ||
                            '        ,SAII_basecof_1  AS "BASE COFINS$SUM"                                                                                                                                                           '||CHR(13) ||
                            '        , SAII_cstcofi_1  AS "CST COFINS"                                                                                                                                                               '||CHR(13) ||
                            '        ,SAII_aliqcof_1 as "ALIQ. COFINS"                                                                                                                                                               '||CHR(13) ||
                            '        ,SAII_valocof_1  AS "VALOR COFINS$SUM"                                                                                                                                                            '||CHR(13) ||
                            '        ,saii_vbcufdest_1 as "BASE DIF DEST$SUM"                                                                                                                                                           '||CHR(13) ||
                            '        ,saii_vicmsufdest_1 AS "DIFAL_DEST$SUM"                                                                                                                                                            '||CHR(13) ||
                            '        ,saii_vbcufdest_1 AS "BASE_DIF_REMET$SUM"                                                                                                                                                            '||CHR(13) ||
                            '        ,saii_vicmsufremet_1 AS "DIFAL_REMET$SUM"                                                                                                                                                            '||CHR(13) ||
                            '        ,saii_vbcufdest_1 AS "BASE_FCP$SUM"                                                                                                                                                            '||CHR(13) ||                           
                            '        ,saii_vfcpufdest_1 AS "VALOR_FCP$SUM"                                                                                                                                                            '||CHR(13) ||                                                      
                            '        ,0 AS "BASE ICMS ST COMPL$SUM"                                                                                                                                                            '||CHR(13) ||                                                      
                            '        ,0 AS "VALOR ICMS ST COMPL$SUM"                                                                                                                                                            '||CHR(13) ||                                                      
                            '        FROM NOTSAII                                                                                                                                                                                    '||CHR(13) ||
                            '        LEFT JOIN NOTSAI ON                     TSAI_EMITENT_1 = SAII_EMITENT_1 AND                                                                                                                     '||CHR(13) ||
                            '                            TSAI_NRONOTA_1 =  SAII_NRONOTA_1 AND                                                                                                                                        '||CHR(13) ||
                            '                            TSAI_SERNOTA_1 = SAII_SERNOTA_1                                                                                                                                             '||CHR(13) ||
                            '        LEFT JOIN V_EMITENTE ON TSAI_EMITENT_1 = COD                                                                                                                                                '||CHR(13) ||
                            '        LEFT JOIN SINCAD     ON  TSAI_CLIENTE_1  = NCAD_CGCOCPF_2                                                                                                                                       '||CHR(13) ||
                            '        LEFT JOIN SINTAB01   ON  NCAD_CODMUNI_2 = NTAB_CODMUNI_1                                                                                                                                        '||CHR(13) ||
                            '        LEFT JOIN SINTAB24 ON SAII_TIPONOT_1 = NTAB_TIPONFS_24                                                                                                                                          '||CHR(13) ||
                            '        LEFT JOIN SINTAB23 ON NTAB_CODLIVR_24 = NTAB_CODIGOS_23                                                                                                                                         '||CHR(13) ||
                            '        WHERE     TSAI_SITUACA_1 <> ''C''                                                                                                                                                                 '||CHR(13) ||
                            '                  AND ( ''S'' = SUBSTR( '||''''|| p_tp_entsai ||'''' ||' ,1,1) )                                                                                                                              '||CHR(13) ||
                            '                  AND  TSAI_EMISDAT_1 BETWEEN ' || ''''||p_dt_dataini||'''' ||'  AND ' ||''''|| p_dt_datafin ||''''       ||'                                                                                                                 '||CHR(13) ||
                            '                   and (  SAII_EMITENT_1 = CAST( SUBSTR( '||''''||p_cd_empresa|| ''''||' , 1,3) AS INTEGER) OR   CAST( SUBSTR( '||''''||p_cd_empresa||'''' ||' , 1,3) AS INTEGER)  = 0 )                                              '||CHR(13) ||
                            '                  AND TSAI_SITUACA_1 <> ''C''                                                                                                                                                             '||CHR(13) ||
                            '                  AND  EXISTS ( SELECT 1 FROM  (' || V_UNION_EXISTS || ' ) ESCMV WHERE                                                                                                                  '||CHR(13) ||
                            '                                EMPRESA  = TSAI_EMITENT_1 AND                                                                                                                                           '||CHR(13) ||
                            '                                ESCM_TIPOREG_1 =  ''S'' AND                                                                                                                                                '||CHR(13) ||
                            '                                ESCM_NRONOTA_1 =  SAII_NRONOTA_1 AND                                                                                                                                    '||CHR(13) ||
                            '                                ESCM_SERNOTA_1 = SAII_SERNOTA_1 AND                                                                                                                                     '||CHR(13) ||
                            '                                ESCM_ESPNOTA_1 = TSAI_ESPNOTA_1      )                                                                                                                                        '||CHR(13) ||
                            '        UNION ALL                                                                                                                                                                                       '||CHR(13) ||
                            '                                                                                                                                                                                                        '||CHR(13) ||
                            '        /*ESCRITA*/                                                                                                                                                                                     '||CHR(13) ||
                            '         SELECT                                                                                                                                                                                         '||CHR(13) ||
                            '         TIPO AS "TIPO"                                                                                                                                                                                 '||CHR(13) ||
                            '        ,''ESCMV, ESCIT'' AS "ARQUIVO#"                                                                                                                                                                     '||CHR(13) ||
                            '        , CASE WHEN                                                                                                                                                                                     '||CHR(13) ||
                            '          CASE WHEN ( BASE_PIS > 0 OR BASE_COFINS  > 0 ) AND NTAB_PISCOFI_23 = 0  THEN 0                                                                                                                '||CHR(13) ||
                            '                ELSE 1 END  =  0 THEN   ''#EC7063''  END  AS "SBI_COLOR"                                                                                                                                  '||CHR(13) ||
                            '        , EMITENTE AS "EMPRESA*"                                                                                                                                                                        '||CHR(13) ||
                            '        ,NOTA             AS  "NOTA"                                                                                                                                                                     '||CHR(13) ||
                            '        ,ESPECIE         AS  "ESPECIE"                                                                                                                                                                  '||CHR(13) ||
                            '        ,CFOP             AS  "CFOP"                                                                                                                                                                     '||CHR(13) ||
                            '        ,LPAD(CAST(tp_lanc AS VARCHAR),3,''0'')||'' - ''||NTAB_DESCRIC_23     AS  "TIPO LANÇAMENTO"                                                                                                         '||CHR(13) ||
                            '        ,DATA_EMISSAO         AS  "DATA EMISSÃO"                                                                                                                                                         '||CHR(13) ||
                            '        ,DATA_LANCAMENTO     AS  "DATA LANÇAMENTO"                                                                                                                                                      '||CHR(13) ||
                            '        ,DATA_ENTRADA         AS  "DATA ENTRADA"                                                                                                                                                         '||CHR(13) ||
                            '        ,( CASE WHEN TIPO =  ''S'' THEN  DESTINATARIO  ELSE CD_EMITENTE END )     AS  "EMITENTE/DESTINATARIO"                                                                                                '||CHR(13) ||
                            '        ,NCAD_NOMECLI_2          AS  "NOME"                                                                                                                                                             '||CHR(13) ||
                            '        ,UF             AS  "UF"                                                                                                                                                                           '||CHR(13) ||
                            '        ,CHAVE_NFE               AS  "CHAVE DE ACESSO"                                                                                                                                                  '||CHR(13) ||
                            '        ,VALOR_CONTABIL   AS "VALOR CONTABIL$SUM"                                                                                                                                                       '||CHR(13) ||
                            '        ,X.CODIGO         AS  "CODIGO"                                                                                                                                                                   '||CHR(13) ||
                            '        ,DESCRICAO         AS "DESCRIÇÃO"                                                                                                                                                                 '||CHR(13) ||
                            '        ,NCM             AS "NCM"                                                                                                                                                                       '||CHR(13) ||
                            '        ,QUANTIDADE             AS "QUANTIDADE$Q"                                                                                                                                                          '||CHR(13) ||
                            '        ,case when QUANTIDADE = 0 then 0 else VALOR_TOTAL      / QUANTIDADE        END               AS "UNITARIO$"                                                                                     '||CHR(13) ||
                            '        ,VALOR_TOTAL      AS "VALOR TOTAL$SUM"                                                                                                                                                          '||CHR(13) ||
                            '        , 0    AS "DESCONTO$SUM"                                                                                                                                                                        '||CHR(13) ||
                            '        , 0 AS "VALOR FRETE$SUM"                                                                                                                                                                        '||CHR(13) ||
                            '        ,0 AS "DESPESAS ACESSÓRIAS$SUM"                                                                                                                                                                 '||CHR(13) ||
                            '        , BASE_ICMS  AS "BASE ICMS$SUM"                                                                                                                                                                 '||CHR(13) ||
                            '        ,CST             AS "CST"                                                                                                                                                                       '||CHR(13) ||
                            '        , ALIQ_ICMS  AS  "ALIQ. ICMS"                                                                                                                                                                   '||CHR(13) ||
                            '        , VALOR_ICMS    AS "VALOR ICMS$SUM"                                                                                                                                                             '||CHR(13) ||
                            '        ,ICMS_ISENTO         AS "ICMS-ISENTO"                                                                                                                                                           '||CHR(13) ||
                            '        ,ICMS_OUTROS         AS "ICMS-OUTROS"                                                                                                                                                           '||CHR(13) ||
                            '        ,0 AS "BASE ICMS ST$SUM"                                                                                                                                                                        '||CHR(13) ||
                            '        ,0 AS "VALOR ICMS ST$SUM"                                                                                                                                                                       '||CHR(13) ||
                            '        ,0 AS "BASE_IPI$SUM"                                                                                                                                                                            '||CHR(13) ||
                            '        ,'' '' AS "CST IPI"                                                                                                                                                                               '||CHR(13) ||
                            '        ,0 AS "ALIQ. IPI"                                                                                                                                                                               '||CHR(13) ||
                            '        , VALOR_IPI  AS "VALOR IPI$SUM"                                                                                                                                                                 '||CHR(13) ||
                            '        ,BASE_PIS  AS "BASE PIS$SUM"                                                                                                                                                                    '||CHR(13) ||
                            '        , CST_PIS  AS "CST PIS"                                                                                                                                                                         '||CHR(13) ||
                            '        , ALIQ_PIS  AS "ALIQ. PIS"                                                                                                                                                                      '||CHR(13) ||
                            '        , VALOR_PIS AS "VALOR PIS$SUM"                                                                                                                                                                  '||CHR(13) ||
                            '        ,BASE_COFINS  AS "BASE COFINS$SUM"                                                                                                                                                              '||CHR(13) ||
                            '        ,CST_COFINS  AS "CST COFINS"                                                                                                                                                                    '||CHR(13) ||
                            '        , ALIQ_COFINS  as "ALIQ. COFINS"                                                                                                                                                                '||CHR(13) ||
                            '        , VALOR_COFINS  as "VALOR_COFINS$SUM"                                                                                                                                                                '||CHR(13) ||
                            '        , BASE_DIF_DEST  AS "BASE_DIF_DEST$SUM"                                                                                                                                                            '||CHR(13) ||
                            '        , DIFAL_DEST  AS "DIFAL_DEST$SUM"                                                                                                                                                            '||CHR(13) ||
                            '        , BASE_DIF_REMET  AS "BASE_DIF_REMET$SUM"                                                                                                                                                            '||CHR(13) ||
                            '        , DIFAL_REMET  AS "DIFAL_REMET$SUM"                                                                                                                                                            '||CHR(13) ||
                            '        , BASE_FCP  AS "BASE_FCP$SUM"                                                                                                                                                            '||CHR(13) ||                           
                            '        , VALOR_FCP  AS "VALOR_FCP$SUM"                                                                                                                                                            '||CHR(13) ||                           
                            '        , base_icms_comp  AS "BASE ICMS ST COMPL$SUM"                                                                                                                                                            '||CHR(13) ||                           
                            '        , valor_icms_comp  AS "VALOR ICMS ST COMPL$SUM"                                                                                                                                                            '||CHR(13) ||                                                    
                            '        FROM      ( '|| V_UNION_ESCRITA ||'  ) X                                                                                                                                                            '||CHR(13) ||
                            '                LEFT JOIN V_EMITENTE C ON X.EMPRESA = C.COD                                                                                                                                            '||CHR(13) ||
                            '                LEFT JOIN SINCAD     ON ( ( CASE WHEN TIPO =  ''S'' THEN  DESTINATARIO  ELSE CD_EMITENTE END )  = ncad_cgcocpf_2 )                                                                        '||CHR(13) ||
                            '                LEFT JOIN SINTAB01   ON ( NCAD_CODMUNI_2 = NTAB_CODMUNI_1 )                                                                                                                             '||CHR(13) ||
                            '                LEFT JOIN SINTAB23 ON (TP_LANC = NTAB_CODIGOS_23)                                                                                                                                          '||CHR(13) ||
                            '                WHERE    NOT  EXISTS ( SELECT 1 FROM NOTENTI                                                                                                                                            '||CHR(13) ||
                            '                                WHERE                                                                                                                                                                   '||CHR(13) ||
                            '                                X.EMPRESA   = ENTI_EMITENT_1 AND                                                                                                                                        '||CHR(13) ||
                            '                                TIPO =  ''E'' AND                                                                                                                                                         '||CHR(13) ||
                            '                                CD_EMITENTE =  ENTI_FORNECE_1  AND                                                                                                                                      '||CHR(13) ||
                            '                                NOTA =  ENTI_NRONOTA_1 AND                                                                                                                                              '||CHR(13) ||
                            '                                SERIE = ENTI_SERNOTA_1 AND                                                                                                                                              '||CHR(13) ||
                            '                                ESPECIE = ENTI_ESPECIE_1      )                                                                                                                                         '||CHR(13) ||
                            '                AND   NOT   EXISTS ( SELECT 1 FROM NOTSAII                                                                                                                                              '||CHR(13) ||
                            '                                                INNER JOIN NOTSAI ON                                                                                                                                    '||CHR(13) ||
                            '                                           TSAI_EMITENT_1 = SAII_EMITENT_1 AND                                                                                                                          '||CHR(13) ||
                            '                                           TSAI_NRONOTA_1 = SAII_NRONOTA_1 AND                                                                                                                          '||CHR(13) ||
                            '                                           TSAI_SERNOTA_1 = SAII_SERNOTA_1                                                                                                                              '||CHR(13) ||
                            '                                      WHERE                                                                                                                                                             '||CHR(13) ||
                            '                                X.EMPRESA  = TSAI_EMITENT_1 AND                                                                                                                                         '||CHR(13) ||
                            '                                TIPO=  ''S'' AND                                                                                                                                                            '||CHR(13) ||
                            '                                NOTA =  TSAI_NRONOTA_1 AND                                                                                                                                              '||CHR(13) ||
                            '                                SERIE = TSAI_SERNOTA_1 AND                                                                                                                                              '||CHR(13) ||
                            '                                ESPECIE = TSAI_ESPNOTA_1      )                                                                                                                                               '||CHR(13) ||
                            '                 AND ( TIPO = SUBSTR('||''''|| p_tp_entsai ||'''' ||' ,1,1) )                                                                                                                              '||CHR(13) ||
                            '                 and (  X.EMPRESA = CAST( SUBSTR( '||''''||p_cd_empresa ||''''||' , 1,3) AS INTEGER) OR   CAST( SUBSTR( '|| '''' ||p_cd_empresa || '''' ||' , 1,3) AS INTEGER)  = 0 )                                                     '||CHR(13) ||
                            '                AND CASE TIPO  WHEN ''S'' THEN DATA_EMISSAO   ELSE DATA_ENTRADA    END BETWEEN '|| ''''||p_dt_dataini||'''' ||'  AND ' ||''''|| p_dt_datafin ||''''    
                                               
                                                ;
   RETURN V_RESULT;

end $function$
;